import * as THREE from 'three';
import { createStudioPost } from '../render/studio-post.js';
import { refineCharacterMaterials } from '../render/character-materials.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { FightAnimationLibrary } from './animation-library.js?v=combos-20260924-1';
const $=id=>document.getElementById(id);
const scene=new THREE.Scene();scene.background=new THREE.Color('#101318');
const renderer=new THREE.WebGLRenderer({canvas:$('canvas'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.5;
const camera=new THREE.PerspectiveCamera(36,innerWidth/innerHeight,.02,60);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxDistance=12;
scene.add(new THREE.HemisphereLight(0xe7efff,0x393a33,.3));const light=new THREE.DirectionalLight(0xffe8d5,2.4);light.position.set(-3,5,4);light.castShadow=true;light.shadow.mapSize.set(4096,4096);Object.assign(light.shadow.camera,{left:-4,right:4,top:4,bottom:-4});light.shadow.normalBias=.003;scene.add(light);
const rim=new THREE.DirectionalLight(0xbacfff,1);rim.position.set(3,4,-4);scene.add(rim);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0x0b1118,roughness:.87}));floor.rotation.x=-Math.PI/2;floor.position.y=-.006;floor.receiveShadow=true;scene.add(floor);
const grid=new THREE.GridHelper(20,40,0x364754,0x27323b);grid.position.y=-.004;scene.add(grid);
const requestedCharacter=new URLSearchParams(location.search).get('character')||'both';$('character').value=requestedCharacter;
const studioPost=createStudioPost(renderer,scene,camera);
const chars=[];let running=true,phase=0,elapsed=0,maxDuration=1,side=false,skeleton=false,version=0,busy=true;
function selectedCharacters(){return chars.filter(c=>$('character').value==='both'||$('character').value===c.name);}
const originalLabels=new Map([...$('clip').options].map(o=>[o.value,o.textContent]));
function populateClips(){const current=$('clip').value;const visible=selectedCharacters();const available=[...visible[0].lib.metadata.keys()].filter(n=>visible.every(c=>c.lib.metadata.has(n)));$('clip').replaceChildren(...available.map(name=>{const option=document.createElement('option');option.value=name;option.textContent=originalLabels.get(name)||name.replaceAll('_',' ').replace(/^./,s=>s.toUpperCase());return option;}));$('clip').value=available.includes(current)?current:'idle';}
function fit(){const visible=chars.filter(c=>$('character').value==='both'||$('character').value===c.name);for(const c of chars){c.root.visible=visible.includes(c);c.helper.visible=skeleton&&c.root.visible;}const center=visible.length===1?visible[0].root.position.x:0;const wide=['roundhouse','snap_kick','sweep','flying_kick','knocked_down','jump','spin_back_kick','hop_kick','ground_pound','get_up','rage_hit'].includes($('clip').value);const dist=Math.max(5.5,(visible.length===2?5.4:wide?4.4:2.5)/camera.aspect);const rage=$('clip').value==='ground_pound';controls.target.set(center,rage?1.2:.94,0);camera.position.set(center+(side?dist*.9:.5),rage?2.1:1.85,side?dist*.32:rage?Math.max(dist,10.5):dist);controls.update();}
function resize(){renderer.setSize(innerWidth,innerHeight);studioPost.resize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();fit();}window.addEventListener('resize',resize);
function markers(m){return m.contact_frames?.length?m.contact_frames:Object.values(m.beats||{}).flat().concat(m.hold_start_frame?[m.hold_start_frame]:[]).sort((a,b)=>a-b);}
function displayMeta(){const chosen=selectedCharacters();$('meta').textContent=chosen.map(c=>{const m=c.lib.metadata.get($('clip').value);return `${c.name==='sam'?'Sam':'Elon'}: ${m.description} · ${m.frames} frames / ${m.duration.toFixed(2)}s${m.contact_frames?.length?' · contact f'+m.contact_frames.join(', '):''}${m.hold_start_frame?' · held pose from f'+m.hold_start_frame:''}${m.substitution?' · adapted source':''}`;}).join(' | ');$('contact').disabled=!chosen.some(c=>markers(c.lib.metadata.get($('clip').value)).length);$('contact').textContent=$('clip').value.startsWith('victory')?'Key pose':'Contact pose';}
async function select(){const request=++version;busy=true;$('contact').disabled=true;$('error').textContent='';$('status').textContent='Loading animation…';try{const name=$('clip').value;const visible=selectedCharacters();await Promise.all(visible.map(async c=>{const clip=await c.lib.load(name);if(request!==version)return;c.lib.mixer.stopAllAction();const action=c.lib.mixer.clipAction(clip);action.reset().setLoop(THREE.LoopOnce,1);action.clampWhenFinished=true;action.play();c.action=action;c.duration=clip.duration;}));if(request!==version)return;maxDuration=Math.max(...visible.map(c=>c.duration));elapsed=0;phase=0;busy=false;fit();displayMeta();$('status').textContent=`${chars.reduce((n,c)=>n+c.lib.metadata.size,0)} clips available · 30 fps · ${visible.length===2?'shared moves shown':'character move set'}`;poseAt(0);}catch(e){$('error').textContent=e.message;$('status').textContent='Animation failed to load';}}
function poseAt(value){for(const c of selectedCharacters()){if(!c.action)continue;c.action.enabled=true;c.action.paused=false;c.action.time=Math.min(value*c.duration,c.duration-.00001);c.lib.mixer.update(0);}phase=value;$('time').value=String(Math.round(value*1000));$('readout').textContent=Math.round(value*100)+'%';}
$('clip').onchange=select;$('character').onchange=()=>{populateClips();select();};$('contact').onclick=()=>{const c=selectedCharacters()[0];const m=c.lib.metadata.get($('clip').value);if(!markers(m).length)return;const times=markers(m).map(f=>(f-1)/30);elapsed=times.find(t=>t>elapsed+.025)??times[0];running=false;$('play').textContent='Play';poseAt(elapsed/maxDuration);};$('play').onclick=()=>{if(!running&&elapsed>=maxDuration&&$('clip').value.startsWith('victory')){elapsed=0;poseAt(0);}running=!running;$('play').textContent=running?'Pause':'Play';};$('time').oninput=()=>{running=false;$('play').textContent='Play';const v=Number($('time').value)/1000;elapsed=v*maxDuration;poseAt(v);};$('view').onclick=()=>{side=!side;$('view').textContent=side?'Front view':'Side view';fit();};$('skeleton').onclick=()=>{skeleton=!skeleton;$('skeleton').classList.toggle('on',skeleton);for(const c of chars)c.helper.visible=skeleton&&c.root.visible;};
async function boot(){try{const loader=new GLTFLoader();for(const [name,ident,x] of [['sam','sam_altman',-.9],['elon','elon_musk',.9]]){const gltf=await loader.loadAsync(new URL(`../models/${ident}.glb?v=likeness-20260924-2`,import.meta.url).href);const root=gltf.scene;refineCharacterMaterials(root,renderer);root.position.x=x;scene.add(root);root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false;}});const helper=new THREE.SkeletonHelper(root);helper.visible=false;scene.add(helper);const lib=await new FightAnimationLibrary(root,name).init();chars.push({name,root,helper,lib});}populateClips();const requestedClip=new URLSearchParams(location.search).get('clip');if(requestedClip&&[...$('clip').options].some(o=>o.value===requestedClip))$('clip').value=requestedClip;resize();await select();}catch(e){$('error').textContent=e.message;$('status').textContent='Character loading failed';}}
resize();let previous=performance.now();renderer.setAnimationLoop(now=>{const dt=Math.min((now-previous)/1000,.08);previous=now;if(running&&!busy){elapsed+=dt*Number($('speed').value);const meta=selectedCharacters()[0].lib.metadata.get($('clip').value);const span=maxDuration+(meta.loop?0:.5);if($('clip').value.startsWith('victory')&&elapsed>=maxDuration){elapsed=maxDuration;running=false;$('play').textContent='Replay';}else if(elapsed>span)elapsed%=span;for(const c of selectedCharacters()){if(!c.action)continue;const time=Math.min(elapsed,c.duration-.00001);c.action.enabled=true;c.action.paused=false;c.action.time=time;c.lib.mixer.update(0);}phase=Math.min(1,elapsed/maxDuration);$('time').value=Math.round(phase*1000);$('readout').textContent=Math.round(phase*100)+'%';}controls.update();studioPost.render();});boot();
