// Sam — short wavy brown hair, neutral expression, taupe crew-neck sweater
// with pushed-up sleeves (bare forearms), grey jeans, light sneakers.
// Sprites get an automatic dark outline at bake time (see pixelart.js).

const SKIN = {
  s: '#eec4a4', S: '#cfa07e', R: '#b3805f',
};
const HAIR = {
  t: '#6a5340', T: '#85684f',
};
const FACE = {
  ...SKIN, ...HAIR,
  b: '#4d3d2e', e: '#221a14', n: '#d7a67f', m: '#a06a58',
};
const SWEATER = {
  U: '#b3968a', u: '#97786c', V: '#74594e', W: '#5c463d', N: '#322c28',
};

export const SAM_PARTS = {
  // compact head sized for the sheet body: brown wavy hair, longer calm face
  smallHead: {
    id: 'sam-head-sm',
    palette: FACE,
    rows: [
      '....ttTttt.....',
      '...tttttttt....',
      '..ttssssssst...',
      '..tssssssst....',
      '..tsesssess....',
      '..tssssssss....',
      '...sssnsssS....',
      '...ssmmsssS....',
      '...ssssssS.....',
      '....SssssS.....',
      '.....sssss.....',
      '.....ssss......',
      '......sss......',
      '......sss......',
    ],
  },
  head: {
    id: 'sam-head',
    palette: FACE,
    rows: [
      '......ttTttt........',
      '....tttttttttt......',
      '...tttTtttttttt.....',
      '...ttsssssssttt.....',
      '...tssssssssstt.....',
      '...tsssssssssst.....',
      '...sbbsssssbbss.....',
      '...ssssssssssss.....',
      '...seesssssseess....',
      '...ssssssssssss.....',
      '...ssssnnssssss.....',
      '...sssssssssssS.....',
      '...ssmmmmmsssSs.....',
      '...ssssssssssSs.....',
      '....ssssssssss......',
      '....SssssssssR......',
      '.....ssssss.........',
      '......ssss..........',
      '......ssss..........',
    ],
  },
  torso: {
    id: 'sam-torso',
    palette: SWEATER,
    rows: [
      '....uuuuuuuuNNuuuuuuuu....',
      '..UuuuuuuuuNNNNuuuuuuuV...',
      '..UUuuuuuuuuNNuuuuuuuVV...',
      '.UUuuuuuuuuuuuuuuuuuuuVV..',
      '.UUuuUuuuuuuuuuuuUuuuuVV..',
      '.UUuuUuuuuuuuuuuuUuuuuVV..',
      '.UUuuUuuuuuuuuuuuUuuuuVV..',
      '.UUuuUuuuuuuuuuuuUuuuuVV..',
      '.UUuuUuuuuuuuuuuuUuuuuVV..',
      '.UUuuUuuuuuuuuuuuUuuuuVV..',
      '.UUuuUuuuuuuuuuuuUuuuuVV..',
      '.UUuuUuuuuuuuuuuuUuuuuVV..',
      '.UUuuUuuuuuuuuuuuUuuuuVV..',
      '.UUuuUuuuuuuuuuuuUuuuuVV..',
      '.UUuuUuuuuuuuuuuuUuuuuVV..',
      '..UuuUuuuuuuuuuuuUuuuVV...',
      '..UuuUuuuuuuuuuuuUuuuVV...',
      '..UuuUuuuuuuuuuuuUuuuVV...',
      '..UuuUuuuuuuuuuuuUuuuVV...',
      '..UuuUuuuuuuuuuuuUuuuVV...',
      '..UuuUuuuuuuuuuuuUuuuVV...',
      '..UuuUuuuuuuuuuuuUuuuVV...',
      '..UuuUuuuuuuuuuuuUuuuVV...',
      '..UuuUuuuuuuuuuuuUuuuVV...',
      '..UuuUuuuuuuuuuuuUuuuVV...',
      '..UuuUuuuuuuuuuuuUuuuVV...',
      '..UuuUuuuuuuuuuuuUuuuVV...',
      '..WuuuuuuuuuuuuuuuuuuWV...',
      '..WWWWWWWWWWWWWWWWWWWWW...',
      '..WWWWWWWWWWWWWWWWWWWWW...',
    ],
  },
  arm: {
    id: 'sam-arm',
    palette: { ...SWEATER, ...SKIN },
    rows: [
      '.UuuuuuV..',
      '.UuuuuuV..',
      '.UuuuuuV..',
      'UUuuuuuVV.',
      'UUuuuuuVV.',
      'UUuuuuuVV.',
      'UUuuuuuVV.',
      'UUuuuuuVV.',
      'UUuuuuuVV.',
      'UUuuuuuVV.',
      'UUuuuuuVV.',
      'UUuuuuuVV.',
      '.WWWWWWW..',
      '.sssssSS..',
      '.sssssSS..',
      '.ssssssS..',
      '.ssssssS..',
      '.sssssSR..',
      '.ssssssS..',
      '.ssssssS..',
      '.sssssSR..',
      '.ssssssS..',
      '.ssssssS..',
      '.sssssSS..',
      '.ssssssS..',
      '.sssssSR..',
      '.ssssssS..',
      '.sssssSR..',
      '..ssssS...',
      '..ssss....',
    ],
  },
  leg: {
    id: 'sam-leg',
    palette: {
      P: '#5a6674', p: '#454e5c', d: '#363d49', D: '#2a3039',
      f: '#e2e4e6', F: '#f6f6f4', C: '#b8bcc0',
    },
    rows: [
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppd...',
      '..Ppppppd...',
      '..Ppppppd...',
      '..Ppppppd...',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppd...',
      '...Pppppd...',
      '...Ppppd....',
      '...Ppppd....',
      '...Ppppd....',
      '...Ppppd....',
      '...ffffF....',
      '..ffffffF...',
      '.ffffffffF..',
      '.fffffffffF.',
      '.fffffffffF.',
      '.CCCCCCCCCC.',
    ],
  },
};
