// Dario — curly grey-flecked hair, round glasses, grin, navy knit blazer
// over a darker navy shirt. Grids face RIGHT; '.' = transparent.
// Sprites get an automatic dark outline at bake time (see pixelart.js).

const SKIN = {
  s: '#efc39f', S: '#cf9d78', R: '#b57f5e',
};
const HAIR = {
  h: '#5f4a38', H: '#7d6349', G: '#9a8a75',
};
const FACE = {
  ...SKIN, ...HAIR,
  b: '#4a3828', g: '#2b3c52', e: '#1d1712', L: '#cfd8de',
  n: '#d8a37c', w: '#f7f3ea', m: '#7c3f34',
};
const SUIT = {
  J: '#4a6288', j: '#364a6e', d: '#293a5a', D: '#1f2d47',
  k: '#23364f', K: '#2e4566', B: '#101b2c',
};

export const DARIO_PARTS = {
  // compact head sized for the sheet body (~15px): grey-brown curls,
  // glasses band with glints, grin — reads at fight zoom without bobblehead
  smallHead: {
    id: 'dario-head-sm',
    palette: FACE,
    rows: [
      '...hGhHhh......',
      '..hGhhhhHh.....',
      '.hhhssssshh....',
      '.hGsssssssh....',
      '.hsgLgggLgs....',
      '.hsssssssss....',
      '..ssssnsssS....',
      '..smwwwwmsS....',
      '..sssssssS.....',
      '...SsssssS.....',
      '....sssss......',
      '.....ssss......',
      '......sss......',
      '......sss......',
    ],
  },
  head: {
    id: 'dario-head',
    palette: FACE,
    rows: [
      '.....hHhGhHh........',
      '...hGhhhhhhhhH......',
      '..hhhHhGhhHhhhh.....',
      '..hHhhhhhhhhhGhh....',
      '.hhGhssssssshhhh....',
      '.hhhsssssssssshhh...',
      '.hGsssssssssssshh...',
      '.hsbbssssbbssssh....',
      '.sgLeLgssgLeLgss....',
      '.sgggggssgggggss....',
      '.ssssssssssssssS....',
      '.ssssssnnsssssSs....',
      '.sssssssssssssSs....',
      '.ssmwwwwwwwmssSs....',
      '.sssmmmmmmmssSss....',
      '..ssssssssssssS.....',
      '..SssssssssssR......',
      '...ssssssssss.......',
      '....sssssss.........',
      '......sssss.........',
      '......sssss.........',
    ],
  },
  torso: {
    id: 'dario-torso',
    palette: SUIT,
    rows: [
      '..jjjjjjjjjjkkjjjjjjjjjj..',
      '.JjjjjjjjjjkKkjjjjjjjjjd..',
      '.JJjjjjjjjjkKkjjjjjjjjdd..',
      '.JJjjjjjjjjkKkjjjjjjjjdd..',
      '.JJjjjjjjjjjkKjjjjjjjjdd..',
      '.JJjjjjjjjjjkKjjjjjjjjdd..',
      '.JJjjjjjjjjjjKjjjjjjjjdd..',
      '.JJjjjjjjjjjjKjjjjjjjjdd..',
      '.JJjjjjjjjjjjBjjjjjjjjdd..',
      '.JJjjjjjjjjjjjjjjjjjjjdd..',
      '.JJjjjjjjjjjjjjjjjjjjjdd..',
      '.JJjjjjjjjjjjBjjjjjjjjdd..',
      '.JJjjjjjjjjjjjjjjjjjjjdd..',
      '.JJjjjjjjjjjjjjjjjjjjjdd..',
      '.JJjjjjjjjjjjjjjjjjjjjdd..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..JjjjjjjjjjjjjjjjjjjjdD..',
      '..DjjjjjjjjjjjjjjjjjjjDD..',
      '..DDDDDDDDDDDDDDDDDDDDDD..',
    ],
  },
  arm: {
    id: 'dario-arm',
    palette: { ...SUIT, ...SKIN },
    rows: [
      '.Jjjjjjd..',
      '.Jjjjjjd..',
      '.Jjjjjjd..',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      'JJjjjjjdd.',
      '.Djjjjdd..',
      '.DDDDDDD..',
      '.sssssSS..',
      '.sssssSS..',
      '.ssssssS..',
      '.ssssssS..',
      '.sssssSR..',
      '.ssssssS..',
      '.sssssSR..',
      '..ssssS...',
      '..ssss....',
    ],
  },
  leg: {
    id: 'dario-leg',
    palette: {
      P: '#4a4a58', p: '#34343f', d: '#26262e', D: '#1c1c23',
      f: '#2a2118', F: '#3d3226', C: '#14100c',
    },
    rows: [
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '.PPppppppdd.',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppd...',
      '..Ppppppd...',
      '..Ppppppd...',
      '..Ppppppd...',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppdd..',
      '..Ppppppd...',
      '...Pppppd...',
      '...Ppppd....',
      '...Ppppd....',
      '...Ppppd....',
      '...Ppppd....',
      '...ffffF....',
      '..ffffffF...',
      '.ffffffffF..',
      '.fffffffffF.',
      '.fffffffffF.',
      '.CCCCCCCCCC.',
    ],
  },
};
