// Stage definitions. `kind: 'hdri'` stages are photographic: a real CC0
// panorama from Poly Haven lights the scene and forms the backdrop, a PBR
// texture set covers the floor, and glTF props dress the arena.
// `kind: 'procedural'` stages are built entirely from geometry and shaders.
export const STAGES = [
  {
    id: 'colosseum',
    kind: 'hdri',
    name: 'COLOSSEUM',
    tagline: 'ROME · MIDDAY · PIAZZA DEL COLOSSEO',
    hdri: 'colosseum',
    rotation: 2.5,
    bgIntensity: 1.25,
    envIntensity: 1.0,
    props: 'colosseum',
    models: ['gothic_statue', 'marble_bust_01', 'horse_statue_01', 'stone_fire_pit', 'boulder_01', 'rock_07', 'namaqualand_boulder_02', 'wooden_crate_01', 'wooden_bucket_01', 'ceramic_vase_03', 'kite_shield', 'shrub_02', 'dead_tree_trunk_02', 'wooden_military_crate'],
    floor: { texture: 'gravelly_sand', uvScale: 0.55, reflBase: 0.06, fade: [10, 17] },
    lights: {
      key: { color: '#fff3e0', intensity: 260, pos: [-6, 11, 4] },
      fill: { color: '#cfe3ff', intensity: 40, pos: [8, 6, 6] },
      rim: { color: '#ffd9b0', intensity: 60, pos: [5, 5, -7] },
      back: { color: '#ffffff', intensity: 0, pos: [0, 8, -8] },
    },
    exposure: 0.95,
  },
  {
    id: 'octagon',
    kind: 'hdri',
    name: 'THE OCTAGON',
    tagline: 'MAIN EVENT · ARENA · SOLD OUT',
    hdri: 'circus_arena',
    rotation: -1.57,
    bgIntensity: 0.7,
    envIntensity: 1.1,
    props: 'octagon',
    models: ['metal_stool_03', 'wooden_bucket_02', 'plastic_monobloc_chair_01', 'concrete_road_barrier_02', 'Megaphone_01', 'vintage_video_camera', 'plastic_bottle_gallon', 'WetFloorSign_01', 'plastic_crate_01', 'security_camera_01'],
    floor: { texture: 'rubber_tiles', uvScale: 0.9, reflBase: 0.12, fade: [12, 20] },
    lights: {
      // overhead cage key straight above the fighters, low front fill, twin white rims
      key: { color: '#fff6ea', intensity: 420, pos: [0, 11, 2.5], angle: 0.785, penumbra: 0.85 },
      fill: { color: '#f2f5ff', intensity: 45, pos: [0, 6.5, 6] },
      rim: { color: '#ffe9d6', intensity: 140, pos: [-6, 7, -6] },
      back: { color: '#eef3ff', intensity: 140, pos: [6, 7, -6] },
    },
    exposure: 0.95,
  },
  {
    id: 'office',
    kind: 'hdri',
    name: 'DEAD OFFICE',
    tagline: 'FLOOR 14 · Q3 LAYOFFS · LIGHTS STILL ON',
    hdri: 'abandoned_factory_canteen_01',
    rotation: -1.57,
    bgIntensity: 1.0,
    envIntensity: 0.6,
    props: 'office',
    models: ['metal_office_desk', 'SchoolChair_01', 'modern_arm_chair_01', 'mounted_fluorescent_lights', 'metal_trash_can', 'cardboard_box_01', 'modular_electric_cables', 'classic_laptop', 'office_notepads', 'stationery_supplies', 'wall_clock', 'potted_plant_02', 'WetFloorSign_01', 'korean_fire_extinguisher_01', 'trashbag', 'wooden_bookshelf_worn', 'drawer_cabinet', 'worn_metal_rack', 'ladder_sectioned_01', 'wheelchair_01', 'plastic_crate_02', 'security_camera_01'],
    floor: { texture: 'dirty_carpet', uvScale: 0.6, reflBase: 0.04, fade: [11, 18] },
    lights: {
      key: { color: '#eaf2e6', intensity: 110, pos: [-2, 6.5, 4] },
      fill: { color: '#c9d8ff', intensity: 30, pos: [7, 5, 4] },
      rim: { color: '#9fd0b0', intensity: 40, pos: [-6, 4.5, -6] },
      back: { color: '#ffffff', intensity: 25, pos: [5, 5, -7] },
    },
    exposure: 0.9,
  },
  {
    id: 'neon-dojo',
    kind: 'procedural',
    name: 'NEON DOJO',
    tagline: 'BONUS STAGE · RAIN OVER THE OLD CITY',
    props: 'dojo',
    rain: true,
    sky: { top: '#03040a', horizon: '#0b1020', bottom: '#04050a', sun: null },
    fog: { color: '#05070d', density: 0.024 },
    hemi: { sky: '#3a4a6a', ground: '#05060a', intensity: 0.22 },
    env: { a: 3, b: 3, back: '#ffffff', backI: 2, front: '#88aaff', frontI: 1.2, top: '#fff2e0', topI: 2.5, wall: '#0b0d12' },
    lights: {
      key: { color: '#fff1dc', intensity: 170, pos: [-5, 9, 7] },
      fill: { color: 'accentB', intensity: 80, pos: [8, 6, 5] },
      rim: { color: 'accentA', intensity: 110, pos: [-6, 6, -6] },
      back: { color: '#88b4ff', intensity: 60, pos: [6, 7, -7] },
    },
    floor: { wet: 1.0, puddle: 0.52, tint: '#0f1016' },
    exposure: 0.9,
  },
];
